[package]
name = "zxcvbn_wrapper"
version = "0.0.0"
authors = ["Svilen Gospodinov <webmaster@s2g.io>"]
edition = "2018"

[lib]
name = "zxcvbn_wrapper"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.22.0"
zxcvbn = "2.1.1"
